datasource:
  druid:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/t1?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: mayadong
    InitialSize: 3
    maxIdle: 10
    maxWait: 1000
